/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ISDKTransferRouterInterface extends Interface {
  getFunction(
    nameOrSignature: "transferKAP20" | "transferKAP721"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "transferKAP20",
    values: [AddressLike, AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferKAP721",
    values: [AddressLike, AddressLike, BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "transferKAP20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferKAP721",
    data: BytesLike
  ): Result;
}

export interface ISDKTransferRouter extends BaseContract {
  connect(runner?: ContractRunner | null): ISDKTransferRouter;
  waitForDeployment(): Promise<this>;

  interface: ISDKTransferRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  transferKAP20: TypedContractMethod<
    [
      tokenAddr_: AddressLike,
      recipient_: AddressLike,
      amount_: BigNumberish,
      bitkubNext_: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  transferKAP721: TypedContractMethod<
    [
      tokenAddr_: AddressLike,
      recipient_: AddressLike,
      tokenId_: BigNumberish,
      bitkubNext_: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "transferKAP20"
  ): TypedContractMethod<
    [
      tokenAddr_: AddressLike,
      recipient_: AddressLike,
      amount_: BigNumberish,
      bitkubNext_: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferKAP721"
  ): TypedContractMethod<
    [
      tokenAddr_: AddressLike,
      recipient_: AddressLike,
      tokenId_: BigNumberish,
      bitkubNext_: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
