/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TestERC20 } from "./TestERC20";
export type { TestPriceOracle } from "./TestPriceOracle";
export type { TestPriceOracleCaller } from "./TestPriceOracleCaller";
export type { TestRandomOracle } from "./TestRandomOracle";
export type { TestRandomOracleCaller } from "./TestRandomOracleCaller";
