/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPriceOracle } from "./IPriceOracle";
export type { IPriceOracleCaller } from "./IPriceOracleCaller";
export type { IRandomOracle } from "./IRandomOracle";
export type { IRandomOracleCaller } from "./IRandomOracleCaller";
export type { ISignalTicket } from "./ISignalTicket";
export type { IToppSignalPool } from "./IToppSignalPool";
