/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRandomOracleCaller,
  IRandomOracleCallerInterface,
} from "../../../contracts/interfaces/IRandomOracleCaller";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "time",
        type: "uint256",
      },
      {
        internalType: "uint256[]",
        name: "values",
        type: "uint256[]",
      },
    ],
    name: "fulfillRandomness",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRandomOracleCaller__factory {
  static readonly abi = _abi;
  static createInterface(): IRandomOracleCallerInterface {
    return new Interface(_abi) as IRandomOracleCallerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRandomOracleCaller {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IRandomOracleCaller;
  }
}
