/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRandomOracle,
  IRandomOracleInterface,
} from "../../../contracts/interfaces/IRandomOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "time",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "requestRandomness",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRandomOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IRandomOracleInterface {
    return new Interface(_abi) as IRandomOracleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRandomOracle {
    return new Contract(address, _abi, runner) as unknown as IRandomOracle;
  }
}
