/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TestERC20__factory } from "./TestERC20__factory";
export { TestPriceOracle__factory } from "./TestPriceOracle__factory";
export { TestPriceOracleCaller__factory } from "./TestPriceOracleCaller__factory";
export { TestRandomOracle__factory } from "./TestRandomOracle__factory";
export { TestRandomOracleCaller__factory } from "./TestRandomOracleCaller__factory";
